spring.application.name=miniaws
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/miniaws
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.embedding.model=llama3.2:3b

# Vector Store (ChromaDB)
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=miniaws_vectors
spring.ai.vectorstore.chroma.initialize-schema=true

# Proxmox
proxmox.api.url=https://192.168.10.128:8006/api2/json/  
proxmox.api.token=root@pam!miniaws=6bc2c73c-75ab-4238-b4e0-6dc554e08792
proxmox.node.name=pve

# D�sactiver Spring Security temporairement pendant le dev
spring.security.user.name=admin
spring.security.user.password=admin123

server.port=8080
proxmox.quota.global.max-ram=10240
proxmox.quota.global.max-cpu=10

# Le Super Administrateur de MiniAWS
miniaws.admin.email=abdelhamid@emsi.ma